### PR TITLE
Breaking

### PR DESCRIPTION
**Pull request by notlee**
See https://github.com/Financial-Times/o-teaser-collection/issues/35

### CODE REVIEW

**Comment by notlee** [comment]
Comment test with hub

**Comment by notlee** [comment]
test

**Comment by notlee** [comment]
o-teaser-collection bundle size difference from 2.3.3 to ea52fe78b2331f19c8d6006e723b113b257958bf
css: 2.25kb decrease (-0.06kb/gzip)

**Comment by notlee** [comment]
o-teaser-collection bundle size difference from 2.3.3 to ea52fe78b2331f19c8d6006e723b113b257958bf
css: 2.25kb decrease (-0.06kb/gzip)

**Comment by notlee** [comment]
test

**Comment by notlee** [comment]
test

**Comment by notlee** [comment]
${BUNDLE_SIZE_MESSAGE}

**Comment by notlee** [comment]
37

**Comment by notlee** [comment]
test

**Comment by notlee** [comment]
o-teaser-collection bundle size difference from 2.3.3 to 263260e94036f0ed6c2496464c1fed567cd77691
css: 2.25kb decrease (-0.06kb/gzip)

**Comment by notlee** [comment]
o-teaser-collection bundle size difference from 2.3.3 to 263260e94036f0ed6c2496464c1fed567cd77691 css: 2.25kb decrease (-0.06kb/gzip)}

**Comment by notlee** [comment]
o-teaser-collection bundle size difference from 2.3.3 to 263260e94036f0ed6c2496464c1fed567cd77691
css: 2.25kb decrease (-0.06kb/gzip)

**Comment by notlee** [comment]
o-teaser-collection bundle size difference from 2.3.3 to 263260e94036f0ed6c2496464c1fed567cd77691
css: 2.25kb decrease (-0.06kb/gzip)

**Comment by origamiserviceuser** [comment]
o-teaser-collection bundle size difference from 2.3.3 to 83f7c451e306189602c1e1e9332b5c3d0f5b630a
css: 2.25kb decrease (-0.06kb/gzip)

**Comment by origamiserviceuser** [comment]
o-teaser-collection bundle size difference from 2.3.3 to a383e3433cf04c82d34e523e55f9ef6b0a018904
css: 2.25kb decrease (-0.06kb/gzip)

**Comment by origamiserviceuser** [comment]
o-teaser-collection bundle size difference from 2.3.3 to cbdfa60d8432062e394de2ec003f6aca757f2331
css, master: 1.93kb decrease (0.00kb/gzip)

**Comment by origamiserviceuser** [comment]
o-teaser-collection bundle size difference from 2.3.3 to 78c1b019c54b936d3ef8c0c0ae530a6a0fe0296c
css, master: 1.97kb decrease (-0.01kb/gzip)

**Pull request merged**
